server:
  port: 8087
spring:
  application:
    name: analytics-service
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: analytics_svc
  flyway:
    enabled: true
    url: ${SUPABASE_MIGRATION_URL}
    user: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    schemas: analytics_svc
    default-schema: analytics_svc
    locations: classpath:db/migration
