server:
  port: 8083
spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  application:
    name: pharmacy-service
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: pharmacy_svc
  flyway:
    enabled: true
    url: ${SUPABASE_MIGRATION_URL}
    user: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    schemas: pharmacy_svc
    default-schema: pharmacy_svc
    locations: classpath:db/migration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka}
