server:
  port: 8083
spring:
  application:
    name: pharmacy-service
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: pharmacy_svc
  flyway:
    enabled: true
    url: ${SUPABASE_MIGRATION_URL}
    user: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    schemas: pharmacy_svc
    default-schema: pharmacy_svc
    locations: classpath:db/migration
