server:
  port: 8082
spring:
  application:
    name: prescription-service
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: prescription_svc
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    url: ${SUPABASE_MIGRATION_URL}
    user: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    schemas: prescription_svc
    default-schema: prescription_svc
    locations: classpath:db/migration

app:
  messaging:
    prescription-queue: ${PRESCRIPTION_QUEUE:prescription_submitted}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.pharmacy.prescription: DEBUG
